### ISSUE TITLE
Dataloading with missing videos

### ISSUE THREAD

**Issue by yuezih** [zhaoyue-zephyrus/AVION#11]
Hi @zhaoyue-zephyrus 

Thank you for your incredible work!

I’m currently pretraining LaViLa on an 8-A800 (80G) node using the following script (with a chunk length of 60 seconds per video):
```
CUDA_VISIBLE_DEVICES=0 \
PYTHONPATH=.:third_party/decord/python/ torchrun \
--nproc_per_node=1 \
scripts/main_lavila_pretrain.py \
--root datasets/Ego4D/video_288px_60sec/ \
--root-val datasets/EK100/EK100_320p_15sec_30fps_libx264/ \
--video-chunk-length 60 \
--use-flash-attn \
--grad-checkpointing \
--use-fast-conv1 \
--batch-size 256 \
--freeze-temperature \
--fused-decode-crop \
--fix-lr \
--output-dir $EXP_PATH 2>&1 | tee $EXP_PATH/log.txt
```

However, the training code gets stuck at [this line](https://github.com/zhaoyue-zephyrus/AVION/blob/31b00b6bc5d2c09f56b90643cd546cfe8a31c005/scripts/main_lavila_pretrain.py#L387):
```
for data_iter, inputs in enumerate(train_loader):
```
And the training process cannot be started.

I noticed that while several (about 9/128) of my CPUs are running at full load, most remain idle. Could you provide some insights into what might be causing this, or suggest ways to improve data loading efficiency?

Thanks in advance!

**Comment by yuezih** [comment]
I just tried to start the training again and was surprised to find that the issue has resolved itself. Everything is running smoothly now.

Sorry for the confusion and any inconvenience caused!

Thanks again for your great work!

**Comment by yuezih** [comment]
The issue was caused by missing videos in my Ego4D dataset. When the video loader attempted to load a missing video, it would get stuck in an infinite loop at [this line](https://github.com/zhaoyue-zephyrus/AVION/blob/31b00b6bc5d2c09f56b90643cd546cfe8a31c005/avion/data/clip_dataset.py#L85), without producing any error message:

```python
while True:
    video_filename = osp.join(root, '{}.{}'.format(vid, ext), '{}.{}'.format(chunk_end, ext))
    if not osp.exists(video_filename):
        # print("{} does not exist!".format(video_filename))
        chunk_end -= chunk_len
```

Once I filtered out the missing videos from annotations, the training ran successfully. I think uncommenting the error message here would be helpful for others to identify the issue:

```python
print("{} does not exist!".format(video_filename))
```

Additionally, I have another question: 
While creating video chunks, I noticed that a few of them are corrupted, causing Decord's VideoReader to fail when loading the video stream during training. Do you have any suggestions or experience in handling this issue?

Thanks a lot!

**Comment by zhaoyue-zephyrus** [comment]
Hi @yuezih 

This is a great point. This error message was used for debugging. If I remember correctly, I didn't see corrupted videos when truncating the video (an example script is here: https://github.com/facebookresearch/LaViLa/blob/main/scripts/crop_and_resize_ego4d.sh). That's why the current implementation does not support interruption for this issue. 

For your case, I would suggest checking your FFMPEG version and watching out for errors. If the error still happens for newer version, simply skipping those video chunks along with their annotated clips would be a solution.  Since the training data is abundant, this won't impact the performance much.

Best,
Yue

**Comment by yuezih** [comment]
Thanks for the prompt reply! My problem is solved and I will close this issue.
