### ISSUE TITLE
Do we have a preprocessed, chunked dataset for EGO4D dataset?

### ISSUE THREAD

**Issue by beitong95** [zhaoyue-zephyrus/AVION#12]
Hi thanks for the amazing repo. I was wondering if you provide chunked and resized EGO4D dataset as EpicKitchen?

**Comment by zhaoyue-zephyrus** [comment]
Hi @beitong95 ,

Thanks for your interest in our work. Ego4D only grants a *non-transferrable* license to use (See [here](https://ego4ddataset.com/ego4d-license/)). Following the license, we are unable to provide the chunked version. However, feel free to download the raw videos on your own and we provide an example script to chunk and resize the raw videos [here](https://github.com/facebookresearch/LaViLa/blob/main/scripts/crop_and_resize_ego4d.sh).

**Comment by beitong95** [comment]
Thank you so much!
