### ISSUE TITLE
How can I Replicate your EK100 Action Recognition results?

### ISSUE THREAD

**Issue by iranroman** [zhaoyue-zephyrus/AVION#6]
Thanks for all this awesome work. 

I see scripts and instructions to do the EK100 MIR task, but not the Action Recognition task. Could you please tell me if I'm missing something? I would like to be able to replicate the Action Recognition performance of 54.4% on the validation split. 

Cheers!

**Comment by zhaoyue-zephyrus** [comment]
Hi @iranroman ,

 We have the instructions included in the readme. Please check out this [page](https://github.com/zhaoyue-zephyrus/AVION/blob/main/docs/MODEL_ZOO.md#ek-100-action-recognition-cls). Thank you!
